name: template-small
container:
  port: 5432
  name:
    default: template-small
    primary: primary
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos8-13.2-4.7.0-beta.3
resources:
  cpu: 200m
  memory: 512Mi
persistence:
  accessModes: ReadWriteMany
